### ISSUE TITLE
Create github release

### ISSUE THREAD

**Issue by fulldecent** [nanotech/phpmyid-oop#1]
Please create a github release to indicate which commit is a stable version.

I'm currently running v0.9 and am not sure if the code here is for testing or if there is an actual release.

**Comment by nanotech** [comment]
I'm not the original phpMyID author, this is just a fork I made a long time ago to improve integration with another codebase. The [official site is over here](https://siege.org/phpmyid.html). Neither has been updated in years though, so you should probably use some other OpenID server that's being maintained.

**Comment by fulldecent** [comment]
Got it, thanks for the pointer!
